version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: spring_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_spring
    ports:
      - "8088:8080"

volumes:
  mysql_data: